version: "3.7"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app-dev
    working_dir: /app-dev
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://appuser:devpassword@db/appdb
      - PYTHONPATH=/app-dev
      - APP_PORT=8000
      - DEBUG=1
    entrypoint: ""
    command: >
      sh -c "alembic upgrade head &&
             cd $$(pwd)/nflrushing &&
             uvicorn main:app --host 0.0.0.0 --reload --port 8000"

  db:
    ports:
      - "5438:5432"
    image: postgres:12.0
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=devpassword
      - POSTGRES_DB=appdb
