version: "3.7"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8000:8000"
    volumes:
      - .:/app-dev
    working_dir: /app-dev
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://appuser:devpassword@db/appdb
      - PYTHONPATH=/app-dev
      - APP_PORT=8000
      - DEBUG=1
    entrypoint: ""
    command: >
      sh -c "./wait-for.sh db:5432 -- alembic upgrade head &&
             uvicorn nflrushing.main:app --host 0.0.0.0 --reload --port 8000"

  client:
    build:
      dockerfile: Dockerfile.client
      context: .
    user: "node"
    working_dir: /app
    depends_on:
      - server
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"

  db:
    ports:
      - "5438:5432"
    image: postgres:12.0
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=devpassword
      - POSTGRES_DB=appdb
